version: "3.8"
services:
  db:
    image: postgres:14-alpine3.18
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
    - 5432:5432
    volumes:
    - ./postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:7.0.11-alpine3.18
    command: --save 20 1 --loglevel verbose --requirepass "redis_password"
    restart: always
    ports:
    - 6379:6379
    volumes:
    - ./redis-data:/data