server:
  http:
    addr: 0.0.0.0:8000
    timeout: 1s
  grpc:
    addr: 0.0.0.0:9000
    timeout: 1s
google:
  client:
    id: "${GOOGLE_CLIENT_ID:google_client_id}"
    secret: "${GOOGLE_CLIENT_SECRET:google_client_secret}"
openai:
  api:
    key: "${OPENAI_API_KEY:openai_api_key}"