server:
  http:
    addr: 0.0.0.0:8000
    timeout: 1s
  grpc:
    addr: 0.0.0.0:9000
    timeout: 1s
  calendar:
    interval: 15s
data:
  database:
    driver: postgres
    source: "${DATABASE_URL:postgres://postgres:postgres@localhost:5432/postgres}"
  redis:
    addr: "${REDIS_URL:localhost:6379}"
    password: "${REDIS_PASSWORD:redis_password}"
    readTimeout: 1s
    writeTimeout: 1s
google:
  client:
    id: "${GOOGLE_CLIENT_ID:google_client_id}"
    secret: "${GOOGLE_CLIENT_SECRET:google_client_secret}"
  redirectUrl: "${GOOGLE_REDIRECT_URL:http://localhost:8000/auth/google/callback}"
openai:
  api:
    key: "${OPENAI_API_KEY:openai_api_key}"
cron:
  jobs:
   - name: "${CRON_JOB_NAME:job_name}"
     schedule: "${CRON_JOB_SCHEDULE:-}"