server:
  http:
    addr: 0.0.0.0:8000
    timeout: 150s
  grpc:
    addr: 0.0.0.0:9000
    timeout: 15s
  tg:
    token: "${TG_TOKEN:telegram_token}"
data:
  database:
    driver: postgres
    source: "${DATABASE_URL:postgres://postgres:postgres@localhost:5432/postgres}"
  redis:
    addr: "${REDIS_URL:localhost:6379}"
    password: "${REDIS_PASSWORD:redis_password}"
    readTimeout: 1s
    writeTimeout: 1s
google:
  client:
    id: "${GOOGLE_CLIENT_ID:google_client_id}"
    secret: "${GOOGLE_CLIENT_SECRET:google_client_secret}"
  redirectUrl: "${GOOGLE_REDIRECT_URL:http://localhost:8000/auth/google/callback}"
openai:
  api:
    key: "${OPENAI_API_KEY:openai_api_key}"
    model: "${OPENAI_MODEL:gpt-3.5-turbo-0613}"
#    model: "${OPENAI_MODEL:gpt-4-0613}"
cron:
  jobs:
   - name: "${CRON_JOB_ONE_NAME:syncLoop}"
     schedule: "${CRON_JOB_ONE_SCHEDULE:@every 150s}"